### ISSUE TITLE
Change the name

### ISSUE THREAD

**Issue by codingoat** [ZsemberiDaniel/KoYDo#1]
This name is simply unacceptable. Please change it ASAP.
My recommendation would be _Kotlin YouTube Downloader Wrapper Library Version 1.0_.
Thanks.

**Comment by ZsemberiDaniel** [comment]
Thanks but "Kotlin YouTube Downloader Wrapper Library Version 1.0" is unacceptable since this is NOT a Java library but a Kotlin library so these long names are not welcome.
